title: Article of the DAY
author: Me, myself
email: juneh.lee@samsung.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. : I Will!
  
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
